# Generated by Django 4.0.5 on 2022-06-18 20:06
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="new_price",
            field=models.PositiveBigIntegerField(null=True, verbose_name="Новая цена"),
        ),
    ]
